### ISSUE TITLE
Extract Features from Construction Permit Data

### ISSUE THREAD

**Issue by eclee25** [codefordc/the-rat-hack#12]
The purpose of this issue is to create a feature engineering script that may be run repeatedly on the occupancy permit dataset, as new entries or files (by year) are added.

This issue was originally posted in the dc_doh_hackathon repository ,which can be found here:
[issue_9](https://github.com/jasonasher/dc_doh_hackathon/issues/9)

Start with the Construction Permit data in the `/Data Sets/Construction Permits/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

Write a script that uses this data to produce a feature data table for 

1. The number of new construction permits issued in the last 4 weeks; and
2. The number of construction permits in effect in each week.

You can find the data format and examples on the `Feature Dataset Format` tab in [this document](https://docs.google.com/spreadsheets/d/1dp82BlwxMHGIiNPjfspWBkp_K1SZox0PXug8J8aOssU/edit#gid=1961157256)

Construction permits can have one or more types, among `"excavation"`, `"fixture"`, `"paving"`, `"landscaping"`, `"projections"`, and `"psrental:`. These are delineated by columns 5-10 in the permit dataset. We will counts permits (potentially more than once) by these 6 classes as well as in total with the type key `"any"`.

**Input:**
CSV files with data for each given year

**Output:**
A script that produces a CSV file with the below format:

-1 row for each feature id, construction permit type and subtype, and each week, year, and census block
-The dataset should include the following columns:

`feature_id`: The ID for the feature, in this case, `"construction_permits_issued_last_4_weeks"` or `"construction_permits_in_effect"`
`feature_type`: Construction permit type as described above, with values in `"excavation"`, `"fixture"`, `"paving"`, `"landscaping"`, `"projections"`, `"psrental"` or `"any"`.
`feature_subtype`: Left blank
`year`: The ISO-8601 year of the feature value
`week`: The ISO-8601 week number of the feature value
`census_block_2010`: The 2010 Census Block of the feature value
`value`: The value of the feature, i.e. the number of construction permits of the specified type either new in the previous 4 weeks or active during the week and year in question in the given census block.

The final script must be able to be run from the command line taking three arguments:
1) A folder with the construction permit data files (the script should concatenate and merge the files in the directory as appropriate)
2) The shapefile for census blocks
3) The output CSV filename

Please also provide a `README.md` that describes the script and how to run it.

You can model the solution for the command line modifications after the files [here](https://github.com/codefordc/the-rat-hack/tree/master/scripts/feature_engineering/extract_311_features/rodent_features) or
[here](https://github.com/codefordc/the-rat-hack/tree/master/scripts/feature_engineering/extract_311_features/non_rodent_features)

Place all of your files in the codefordc/the-rat-hack repository under a new `scripts/feature_engineering/extract_construction_permit_features/` folder

**Comment by nathanielconroy** [comment]
Hey all, I'm making a bit of progress on this, but I'm getting stuck on extracting the census block ids from the shape file. 

I'm essentially following the method in this solution: https://github.com/codefordc/the-rat-hack/blob/master/scripts/feature_engineering/extract_311_features/non_rodent_features/extract_non_rodent_features.py

However, when I run this, the shape file returns a data frame with just a single column for the polygons, but no column for GEOID10. Should I be able to get the census block ids from that shape file, or am I missing a step? Thanks for any advice!

**Comment by jasonasher** [comment]
Hi Nathaniel - which shapefile are you using? When I load the `tl_2016_11_tabblock10.shp` file in the `data/dc_census_block_shapefiles/census_2010/` folder on Dropbox with GeoPandas I get a dataframe that has multiple columns including GEOID10. Send me a note on Slack if this isn't working for you and I'll troubleshoot some more.
